### ISSUE TITLE
Download tiles?

### ISSUE THREAD

**Issue by seedlit** [tudelft3d/geo1101.2020.ahn3#5]
Nice repo!
I was wondering if you have processed all the tiles, and if you offer links to download these tiles?
If not, can you guide me with the naming pattern of original tiles? For instance, tiles are named like this - 06HZ2, 11DN1, etc. Is there a way I can get all the tile names, or if there is a pattern being followed that I am missing?
Thanks.

**Comment by mdjong1** [comment]
Hey @seedlit ,

Unfortunately we don't offer any of the processed tiles as a download; we only stored some of the results temporarily.

The naming scheme of the original tiles is done using a Z-Order, in the pattern seen in this example:
![image](https://user-images.githubusercontent.com/4410453/133082137-48ed8e7f-d9a6-45b2-a452-06ca4ee77254.png)

This is based on the encompassing AHN3 tile index logic (https://geoforum.nl/t/wat-zijn-de-ahn3-bladindex-in-de-hoogtekaart-wfs/5566/21).

Each top Tile

**Comment by seedlit** [comment]
Thanks @mdjong1 for the explanation and quick response.

**Comment by mdjong1** [comment]
btw if this is for your project https://github.com/seedlit/dsm2dtm
I would suggest looking at our repo https://github.com/khalhoz/geo1101-ahn3-GF-and-Interpolation
which contains all of our methodologies used, separately, so they're easier to digest and pick and match

**Comment by seedlit** [comment]
@mdjong1 This is for a different use case. I am trying to generate DSM using only RGB as input using CNN (convolutional neural network). I would still take a look at your repo to see if I can grab some pre-processing steps.

**Comment by seedlit** [comment]
@mdjong1 I created a CSV with all tile names and their bounds, and a script to download tiles intersecting with input AOI for my use case. I am not sure of you actively work with this data, but you might also find it useful - [https://github.com/seedlit/ahn3-downloader](https://github.com/seedlit/ahn3-downloader)

**Comment by mdjong1** [comment]
cool stuff!
